### ISSUE TITLE
Hexadecimal Color Value Displaying Before Name Tag

### ISSUE THREAD

**Issue by gtxzombie** [ShadersAllen/Chat-Processor#19]
Before the name tag in chat, with the chat color plugin that is included, the hexadecimal value for the color that was chosen is being displayed before the tag. The color is working, though.

Example: 
`
	"Admin"
	{
		"flag"		"z"
		"tag"		"[Admin] "
		"tagcolor"	"#f20202"
	}
`
The result of the tag for the users with the z flag is f20202[Admin]"Username". Any fixes?

**Comment by Drixevel** [comment]
What game?

**Comment by gtxzombie** [comment]
@Drixevel CS:GO

**Comment by MitchDizzle** [comment]
Why are you using hexadecimal colors for csgo, as csgo doesn't even support hex colors.
