### ISSUE TITLE
Bara/Store OnSayText2 Issue: "Using two team colors in one message is not allowed"

### ISSUE THREAD

**Issue by kaeming** [ShadersAllen/Chat-Processor#33]
L 04/10/2018 - 08:34:44: [SM] Exception reported: Using two team colors in one message is not allowed
L 04/10/2018 - 08:34:44: [SM] Blaming: store.smx
L 04/10/2018 - 08:34:44: [SM] Call stack trace:
L 04/10/2018 - 08:34:44: [SM]   [0] ThrowError
L 04/10/2018 - 08:34:44: [SM]   [1] Line 422, D:\ChaoFanSEA LATEST\SourceMod\addons\sourcemod\scripting\include\multicolors/colors.inc::C_Format
L 04/10/2018 - 08:34:44: [SM]   [2] Line 379, D:\ChaoFanSEA LATEST\SourceMod\addons\sourcemod\scripting\include\multicolors.inc::CFormatColor
L 04/10/2018 - 08:34:44: [SM]   [3] Line 93, store/cpsupport.sp::CP_OnChatMessage
L 04/10/2018 - 08:34:44: [SM]   [5] Call_Finish
L 04/10/2018 - 08:34:44: [SM]   [6] Line 270, e:\git\Chat-Processor\scripting\chat-processor.sp::OnSayText2
L 04/10/2018 - 08:34:46: [SM] Exception reported: Using two team colors in one message is not allowed
L 04/10/2018 - 08:34:46: [SM] Blaming: store.smx
L 04/10/2018 - 08:34:46: [SM] Call stack trace:
L 04/10/2018 - 08:34:46: [SM]   [0] ThrowError
L 04/10/2018 - 08:34:46: [SM]   [1] Line 422, D:\ChaoFanSEA LATEST\SourceMod\addons\sourcemod\scripting\include\multicolors/colors.inc::C_Format
L 04/10/2018 - 08:34:46: [SM]   [2] Line 379, D:\ChaoFanSEA LATEST\SourceMod\addons\sourcemod\scripting\include\multicolors.inc::CFormatColor
L 04/10/2018 - 08:34:46: [SM]   [3] Line 93, store/cpsupport.sp::CP_OnChatMessage
L 04/10/2018 - 08:34:46: [SM]   [5] Call_Finish
L 04/10/2018 - 08:34:46: [SM]   [6] Line 270, e:\git\Chat-Processor\scripting\chat-processor.sp::OnSayText2

**Comment by kaeming** [comment]
lol nvm, nothing to do with cp, it's a problem with cpsupport.
solved.

**Comment by mgeerse** [comment]
> 
> 
> lol nvm, nothing to do with cp, it's a problem with cpsupport.
> solved.

Would you mind sharing what you did to solve this issue?
